#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $RIZ_REPO == "DEADLY_SPAM_BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWV9GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $RIZ_REPO == "DEADLY_SPAM_BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWV9GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $RIZ_REPO =~ $regex ]]
    then
        if [[ $RIZ_REPO_BRANCH ]]
        then
            echo "${RIZ_REPO}/archive/${RIZ_REPO_BRANCH}.zip"
        else
            echo "${RIZ_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWV9GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="DeadlyOp.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    RIZPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $RIZPATH
    echo "    Starting DEADLY SPAM BOT    "
    echo "
                    DEADLY OP BOT
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m DeadlyOp
}

_set_bot
